In [20]:
class Activation_Sigmoid:
	def forward(self, inputs):
		self.inputs = inputs
		self.output = 1/(1+np.exp(-1*inputs))

class Activation_ReLU:
	def forward(self, inputs):
		self.inputs = inputs
		self.output = np.maximum(0, self.inputs)

inputs = np.array([[1,2,3,4], [-1,-2,-3,-4]])
activation_sig = Activation_Sigmoid()
activation_sig.forward(inputs)
activation_relu = Activation_ReLU()
activation_relu.forward(inputs)

print(f'sigmoid\n{activation_sig.output}\n')
print(f'sigmoid\n{activation_relu.output}\n')

sigmoid
[[0.73105858 0.88079708 0.95257413 0.98201379]
 [0.26894142 0.11920292 0.04742587 0.01798621]]

sigmoid
[[1 2 3 4]
 [0 0 0 0]]



In [11]:
import numpy as np
np.random.seed(1)
inputs = np.array([[1,2,3,4], 
					[5,6,7,8], 
					[9,10,11,12]])

class Dense_Layer:
	def __init__(self, n_inputs, n_neurons):
		self.biases = np.zeros((1, n_neurons))
		self.weights = np.random.randn(n_inputs, n_neurons)
	def forward(self, inputs):
		self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
	def forward(self, inputs):
		self.inputs = inputs
		self.output = np.maximum(0, self.inputs)

class Activation_Sigmoid:
	def forward(self, inputs):
		self.inputs = inputs
		self.output = 1/(1+np.exp(-1*inputs))

layer1 = Dense_Layer(4, 3)
layer1.forward(inputs)

activation1 = Activation_ReLU()
activation1.forward(layer1.output)

activation2 = Activation_Sigmoid()
activation2.forward(layer1.output)
print(f'input:\n{inputs}\n')
print(f'Layer1:\n{layer1.output}\n')
print(f'Activation_ReLU:\n{activation1.output}\n')
print(f'Activation_Sigmoid:\n{activation2.output}\n')

input:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Layer1:
[[  3.71536191   4.68386989 -12.4146947 ]
 [ 11.90263443   8.5020789  -30.69794295]
 [ 20.08990695  12.32028791 -48.9811912 ]]

Activation_ReLU:
[[ 3.71536191  4.68386989  0.        ]
 [11.90263443  8.5020789   0.        ]
 [20.08990695 12.32028791  0.        ]]

Activation_Sigmoid:
[[9.76232041e-01 9.90841479e-01 4.05849333e-06]
 [9.99993228e-01 9.99796995e-01 4.65642672e-14]
 [9.99999998e-01 9.99995540e-01 5.34243130e-22]]

